[package]
name = "tower-in-flight-limit"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
tower = { version = "0.1", path = "../" }
tower-ready-service = { version = "0.1", path = "../tower-ready-service" }
